// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsXR2NV1TpgcApNVjHrq2gwHs--hcOq1M',
    appId: '1:651049233839:web:fa21a019aaa0002427935a',
    messagingSenderId: '651049233839',
    projectId: 'sahtin-2fc80',
    authDomain: 'sahtin-2fc80.firebaseapp.com',
    databaseURL: 'https://sahtin-2fc80-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sahtin-2fc80.firebasestorage.app',
    measurementId: 'G-6LTL71G9BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsQTdV4h0UjwX-2l6QmmlDdlzsEhdIrCk',
    appId: '1:651049233839:android:f678c3487ea1a4b027935a',
    messagingSenderId: '651049233839',
    projectId: 'sahtin-2fc80',
    databaseURL: 'https://sahtin-2fc80-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sahtin-2fc80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXF3Qj3kevD_me36ApFoqnVP9bmJfrBhQ',
    appId: '1:651049233839:ios:fc2c34503af747ce27935a',
    messagingSenderId: '651049233839',
    projectId: 'sahtin-2fc80',
    databaseURL: 'https://sahtin-2fc80-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sahtin-2fc80.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXF3Qj3kevD_me36ApFoqnVP9bmJfrBhQ',
    appId: '1:651049233839:ios:fc2c34503af747ce27935a',
    messagingSenderId: '651049233839',
    projectId: 'sahtin-2fc80',
    databaseURL: 'https://sahtin-2fc80-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sahtin-2fc80.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsXR2NV1TpgcApNVjHrq2gwHs--hcOq1M',
    appId: '1:651049233839:web:bb669659f2967d4c27935a',
    messagingSenderId: '651049233839',
    projectId: 'sahtin-2fc80',
    authDomain: 'sahtin-2fc80.firebaseapp.com',
    databaseURL: 'https://sahtin-2fc80-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sahtin-2fc80.firebasestorage.app',
    measurementId: 'G-9P5W0TCB3R',
  );
}
